{{- if .Values.api.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "banking-app.fullname" . }}-api
  labels:
    {{- include "banking-app.componentLabels" (dict "component" "api" "Chart" .Chart "Release" .Release "Values" .Values) | nindent 4 }}
    {{- with .Values.api.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "banking-app.componentSelectorLabels" (dict "component" "api" "Chart" .Chart "Release" .Release) | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.api.serviceMonitor.interval }}
{{- end -}}
